#! /usr/bin/env sh

# SPDX-License-Identifier: BSD-2-Clause
# 
# Copyright (c) 2022 Vincent DEFERT. All rights reserved.
# 
# Redistribution and use in source and binary forms, with or without 
# modification, are permitted provided that the following conditions 
# are met:
# 
# 1. Redistributions of source code must retain the above copyright 
# notice, this list of conditions and the following disclaimer.
# 
# 2. Redistributions in binary form must reproduce the above copyright 
# notice, this list of conditions and the following disclaimer in the 
# documentation and/or other materials provided with the distribution.
# 
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS 
# "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT 
# LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS 
# FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE 
# COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, 
# INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, 
# BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; 
# LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER 
# CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT 
# LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN 
# ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE 
# POSSIBILITY OF SUCH DAMAGE.

TOOLCHAIN_PREFIX=csky-elfabiv2
. ${SCRIPTS_DIR}/configure-toolchain.inc

SDK_ARCH=xt804
SDK_INCDIR="${SDK_DIR}/include"

SDK_INCLUDES=

for subdir in $(find ${SDK_INCDIR} -type d); do
    SDK_INCLUDES="${SDK_INCLUDES} -I${subdir}"
done

SDK_LIBDIR="${SDK_DIR}/lib"
SDK_LIBS="-lwmarch -ldrivers -lwmcomponent -ldsp"
SDK_LDSCRIPT="$(find ${SDK_DIR}/ld -type f -name '*.ld')"

SDK_FLASH_TOOL="${SDK_DIR}/tools/wm_tool"

# libwmarch.a = libwmxt804.a = libwmbsp.a + libwmlibc.a
# libdrivers.a
# libwmcomponent.a = libwmrtos.a + auto_dl + fatfs + ascii_fonts
# libwmrtos.a = freertos + libwmportable.a
# libwmportable.a = libptmemmang.a + libptxt804.a
